### ISSUE TITLE
Solvent in Pspc

### ISSUE THREAD

**Issue by dmorse** [dmorse/pscfpp#10]
Implement and test point-particle solvents in the Pspc CPU pseudo-spectral code

- [x]   Add solvents_ and nSolvent_ to Pscf::MixtureTmpl
- [x]  Create Pspc::Solvent class
- [x]  Modify Pspc::Mixtures class, compute and setMesh functions
- [x] Modify  Pspc::System, functions computeFreeEnergy, outputThermo, initHomogeneous.
- [x] Use fortran code to create a reference solution, binary copolymer + solvent in a lamellar phase.
- [x] Check convergence of C++ code for reference solution, superficially compare results, e.g., by checking free energy and manual spot check of fields.
- [x] Create a unit test in pspc/tests/system/SystemTest of binary copolymer / solvent lamellar phase.

**Comment by benmagruder** [comment]
I can do this
