### ISSUE TITLE
Print propagator values to file (pscf_fd)

### ISSUE THREAD

**Issue by debraaudus** [dmorse/pscfpp#107]
As a future feature, it would be very helpful to be able to have access to the propagators at the end of the simulation for further analysis. It seems like this should be relatively easy to implement since it would mainly require printing known quantities to file. Thank you very much for considering this.

**Comment by dmorse** [comment]
This feature exists in pscf_pc and (I think) also pscf_pg programs for periodic structures. The html manual documents several commands with names that start with WRITE_Q_.... for this purpose. See

 https://dmorse.github.io/pscfpp-man/user_command_pc_page.html#user_command_pc_qout_sec

We should add corresponding features to the pscf_fd 1D finite element code.  I've changed the title of the issue to reflect this distinction, and will add this issue to plans for v1.1

Thanks for contributing. Which program are you actually using?

**Comment by debraaudus** [comment]
Thank you for adding this to potential enhancement list and for updating the title to be more precise. We are using pscf_fd as you intuited.

**Comment by chen7545** [comment]
I can do this.

**Comment by dmorse** [comment]
Completed by Kexin Chen, Aug. 2023

**Comment by dmorse** [comment]
Debra, please let me know if this comment gets to you by this mechanism. The ability to write propagators from pscf_fd is currently in the devel branch, and we are approaching the point of merging this into the master branch and tagging it as v1.1.  If you have a chance to try out this branch and let us know if it works well and does what you need, I'd appreciate it. To do so you'd have to checkout the devel branch, and would probably want to use doxygen to generate a local copy of the html manual that includes the documentation for these commands.

**Comment by debraaudus** [comment]
Thank you so much! We will test things out in the next week or so and let you know how it goes.

**Comment by dmorse** [comment]
Great, thanks for beta testing!
