### ISSUE TITLE
Clean up Pspc system regression tests

### ISSUE THREAD

**Issue by dmorse** [dmorse/pscfpp#11]
(1) Organize input files in pspc/tests/system/in into the following subdirectories:

in/diblock/lam/
in/diblock/hex/
in/diblock/bcc/

Each such directory should have files:

     param.flex       - C++ parameter file for flexible iteration (isFlexible false)
     param.rigid     - C++ param file for rigid iteration (isFlexible true)
     script               - Fortran parameter file with domain on
     omega.ref       - converged reference solution, converged with domain on
     omega.in         -  Input omega file, converged at slightly different chi N)

Converged solution omega.ref should be produced by iterating the fortran code to convergence with domain on.   Choose parameters so the solutions are intermediate segregation (not too close to ODT but not too expensive), corresponding to chi N that exceeds the value at the ODT by about 5. Tests of the C++ code with isFlexible false should use a fixed lattice spacing equal to that obtained from this converged solution, to avoid
the need to use different omega reference files to test iteration with rigid and flexible
unit cells. Note that creation of omega.in files requires completion of step (4) below, so these will initially be absent.

(2) Create unit tests that read in the converged omega.ref reference solution, for flexible and rigid unit cells. These will be similar to the current tests except for the input file names.

(3) Compare the way residuals and error criteria are defined in the fortran and C++ codes.  See if they are identical or not.  If identical, check that initial residuals and convergence behaviors are consistent for fortran and C++ code if run using converged solutions read from the same file as inputs.

(4) Create modified omega.in input files for each of these tests in which the input file is obtained from a converged solution at a slightly different value of chi N. For simplicity, use a converged solution for a value of chi N that is less than the target value by 1.0. Add unit tests for flexible unit cells to test convergence from slightly different initial conditions.

**Comment by Anshul05081996** [comment]
I can do this.

**Comment by dmorse** [comment]
Questions remain about agreement regarding the residuals for the same input files, but the files structure has been cleaned up.
