### ISSUE TITLE
Add Sweep functionality to Pspc

### ISSUE THREAD

**Issue by dmorse** [dmorse/pscfpp#14]
Goal: Add sweep functionality to pspc, analogous to that of fortran PSCF code. 

As side product, also create BasisFieldState class, which may be useful as building block for writing more concise regression tests.

- [x] Create skeleton of BasisFieldState class (dmorse)
- [x] Create skeleton for Pspc::Sweep base class (dmorse)
- [x] Implement arbitrary order polynomial extrapolation in Pscf::SweepTmpl, test accuracy in Fd1d
- [x]  Write basic unit test BasisFieldState in pspc/tests/sweep/BasisFieldStateTest
- [x] Create SweepFactory class, initially with no known subclasses.
- [x] Modify System<D> to implement sweep, uncomment some code and modify readParameters
- [x] Add System<D>::sweep command function and sweep command in System::readCommands. Possibility: Use the SweepFactory to read a parameter block from the command file rather than from the parameter file. 
- [x] Write much more general LinearSweep
- [x] Create pspc/tests/sweep/LinearSweepTest class with unit tests

**Comment by rpcollanton** [comment]
I can do this.

**Comment by dmorse** [comment]
Desgn proposal for a Pspc::LinearSweep class:

Create a LinearSweep::Parameter class that can store data change in a single parameter, in 
a format that is general enough to info about any relevant type of parameter.  

A LinearSweep has an array of LinearSweep::Parameter objects,  each of which stores information about 
a change in one parameter.

Example of one possible parameter file format for LinearSweep (first crack):

LinearSweep {
        ns    100
        nParameter   4
        parameters {
             block    0      1       0.2
             kuhn     1     0.5
             chi         0      1      5.0
             phi         0     +0.1
             phi         1     -0.1
        }
}

The file format for different types of parameters can be different but generally involves a key word to identify the type of parameter, one or two integer ids to identify the species, block, monomer index or indices associated with a particular parameter and the change in the value of that parameter over a range 0 <= s <=1. 

The key words, corresponding to different values of a C enumeration are:

 - Type block type represents a block length followed by a species and block index.
 - Type kuhn represents a statistical segment length, followed by a monomer type id.
 - Type solvent represents a solvent volume, followed by a solvent id
 - Type chi represents a Flory-Huggins interaction parameter, followed by two monomer ids
 -  Type phi represents a species volume fraction, followed by a species id
 -  Type mu reprents a species chemical potential, followed by a species id

To simplify enumeration of species ids, we could use a convention in which they are listed consecutively with polymers first, so that a solvent id corresponds to nPolymer + solventId. 

In order to use a single type of object to represent any of these types of variation, the class data format has to be flexible enough to represent any of the above. I suggest a LinearSweep::Parameters class with private data members:

       enumeration LineaSweep::ParameterType (Block, Chi, Phi, Mu, Kuhn, Solvent)
       int id1;
       int id2;
       double   initial_
       double   final_
       double   change_
       System<D>*  systemPtr_

Member functions of LinearSweep::Parameter class :
 
       void readParameters -> read data from file, including type, integer ids and change_
       void writeParameters -> write data back to file in the same format
       void setup  -> called before the beginning of a sweep, sets values of initial and final
       setParameter  - called by Sweep::setParameters to set the value in the associated system

The Sweep setup and setParameters functions can then just include loops over LinearSweep:Parameters objects that call the setup or setParameter function for each.

The cleanest way to read the LinearSweep::ParameterType object is to create overloaded extractor (>>) and inserter (<<) operators for this type of object, which can include if then statements that check for allowed key word string values.
