### ISSUE TITLE
Check basis code for non-centrosymmetric space groups

### ISSUE THREAD

**Issue by dmorse** [dmorse/pscfpp#15]
Both the fortran and C++ basis generation code have been modified to correctly treat closed stars in bases for non-centrosymmetric groups. The original fortran code was based on an incorrect assumption that these stars must be either even or odd under inversion, which was simply false.  This caused errors that appeared only for bases for non-centrosymmetric groups (i.e., no inversion symmetry) that contained closed stars which were neither even nor odd. 

One structure that caused trouble was the C15 Laves phase, which is now the subject of real scientific interest.  The space group for this apparently has two settings, and only one of them causes trouble.  This provides an opportunity to try to test the code by equivalent solutions obtained with these two settings. 

Ben Magruder has experience with this phase, so I'd like him to provide information in this thread about the name of the relevant space group, which setting worked fine and which one created trouble, and (if he knows) whether one or both have inversion symmetry with respect to the origin of space used in the setting.  If the two settings are related by a translation by a fraction of a unit cell, and you know what the relationship is, please record that as well. 

We also need to test and debug the code for pairs of open stars, using the alternating gyroid phase as an example of a phase with no inversion center and many open stars.

Suggested steps:

- [x] Run an old version of the fortran code to create a record of which C15 setting caused trouble,  record the error message, and see if it allows you to pinpoint which star was causing trouble. 
- [x] Use a new version of the C++ code to create unit tests for both settings of the C15 space group in pscf/tests/crystal/BasisTest.h, analogous to the existing testMake3DBasis_I_m_3b_m and testMake3DBasis_I_a_3b_d tests for cubic space groups. This will determine whether basis generation succeeds in isolation of other parts of the scft program.
- [x] Fix bug kgrid <-> basis conversion for open stars, using alternating gyroid as an example
- [x] Add code FieldIo::readFieldsBasis to correct for reversal of the order of pairs of open stars that are related by inverson, using alternating gyroid as an example
- [x] Add example and unit tests for c15 setting 1 in pspc/tests
- [x] Create example for C15 setting 2 for pscfpp and check equality of free energies.
- [x] Create public example and unit test for alternating gyroid for pscfpp at modest chi values.

**Comment by benmagruder** [comment]
I can do this.

**Comment by benmagruder** [comment]
C15 has a space group of Fd-3m, which has two settings that differ by the translation [1/8 1/8 1/8]. Using the notation of PSCF space groups, "F d -3 m : 1" does _not_ have an inversion center in the center of the unit cell, and therefore gave us errors when we used it in PSCF. "F d -3 m : 2" is centrosymmetric, so it never gave us any trouble and was therefore the setting that we have always chosen to use for C15. 

In old versions of PSCF, using "F d -3 m : 1" resulted in the following error:
```
 Error: Last coefficient in closed star has imaginary part
      (-6.49467053291775074E-017,-0.35355339664408242)
 Error: Closed star is neither sine-like or cosine-like
```
In PSCFPP, the error was:
```
Function: void Pscf::Pspc::FieldIo<3>::convertKGridToBasis(const RFieldDft<D> &, DArray<double> &) [D = 3]
Message : Failed assertion: abs(component.imag()) < 1.0E-8
File    : /Users/benmagruder/Documents/research/scft/pscfpp/src/pspc/field/FieldIo.tpp
Line    : 659
```
After enabling the debug prints in basis_mod.f90, Logan identified that the error is triggered by an unexpected phase difference between [1 1 1] and [-1 -1 -1], from the following output:
```
BASIS
group_name
      'F d -3 m : 1'
 get_star star
   0   0   0   0.000   0.000   1
 get_star star
   1   1   1   0.000   0.000   1
   1   1  -1   0.750   0.750   2
   1  -1   1   0.750   0.750   3
  -1   1   1   0.750   0.750   4
   1  -1  -1   0.000   0.000  10
  -1  -1   1   0.000   0.000  11
  -1   1  -1   0.000   0.000  13
  -1  -1  -1   0.750   0.750  20
```
Logan also observed that the error only occurred in alternate settings of centrosymmetric space groups when the inversion center is shifted away from the origin by ±[1/8 1/8 1/8] or ±[3/8 3/8 3/8], but settings in which the inversion center is shifted by ±[1/4 1/4 1/4] did not give an error.
