### ISSUE TITLE
Unnecessary curly braces -- intended behavior?

### ISSUE THREAD

**Issue by gkcheong** [dmorse/pscfpp#3]
Refer to the start of line
https://github.com/dmorse/pscfpp/blob/63b5540fdccf63dc3b29e60c39506ea9ce47684f/src/pscf/crystal/Basis.tpp#L56

Unsure if code within is intended to run. Does the code at any point expect space group files to lie within the same directory?

**Comment by dmorse** [comment]
GK,
     1) The extra curly braces were just there to restrict the scope of the
definition of a file object
          that is declared there.  It may or may not have been a good idea,
but I think it was intentional
          (and it does do something, because of effects on scope).

      2) Yes, the code was designed to allow for the possibility that a
user could provide a space
           group file separate from the set provided with the code, which
they could access by placing
           it in the working directory.

-Dave
