### ISSUE TITLE
Low Priority: Elements of SpaceSymmetry can be compared without assigning to new objects

### ISSUE THREAD

**Issue by gkcheong** [dmorse/pscfpp#4]
https://github.com/dmorse/pscfpp/blob/63b5540fdccf63dc3b29e60c39506ea9ce47684f/src/pscf/crystal/SymmetryGroup.tpp#L176

**Comment by dmorse** [comment]
Agreed that it would be possible to do this without assigning to a new object, with a slight saving in time. These operations are, however, only used during construction and validity checking of the symmetry group, which is done once at the beginning of an SCFT calculation and is a fast operation. I thus think this optimization would have no perceptible effect on the time seen by a user, and find the current code easy to read.  I thus think this is not worth ever worrying about, and so am closing the issue.  There are lots of "low priority" issues that are higher priority than this.
