### ISSUE TITLE
A small bug during installation

### ISSUE THREAD

**Issue by yongdd** [dmorse/pscfpp#5]
During installation, I encountered a small bug. When I typed "make all-cpu" twice in a row, I got a message like "No rule to make target ...".

It seems that white spaces are missing between filenames in the middle of "fd1d/iterator/Iterator.d" and "fd1d/iterator/NrIterator.d".

If you do not make a new line between filenames, there should be a white space between them. So I think that "lib/python/pscfpp/TextWrapper.py" need to be modified as below

```
   def append(self, string):
      size = len(string)
      if (self.column + size > self.limit):
         self.text += self.eol
         for i in range(self.nIndent):
            self.text += ' '
         self.column = self.nIndent
      elif (self.column > 0):
         self.text += ' '
         self.column += 1
      self.text += string
      self.column += size
```

I'm new to this code, so it could be my ignorance.

Thank you for making these programs and sharing them.

Best Regards.

**Comment by dmorse** [comment]
Thanks very much for the report and solution. I implemented the change you suggested
and pushed it to the master branch.  Whether this problem appears must depend on the
length of the absolute path strings, which will be different for different users. I didn't 
encounter the problem. I'd appreciate it if you could pull a new version and confirm that
the change fixed your problem.

**Comment by yongdd** [comment]
As you suggested, I pulled the new version and confirmed that everything works fine.
Thank you very much. I'm so surprised that you answered this issue so quickly!
