### ISSUE TITLE
PSCF online tutorial inducing error in setting environment variables

### ISSUE THREAD

**Issue by MateusGarciaRodolfo** [dmorse/pscfpp#64]
https://dmorse.github.io/pscfpp-man/install_environment_page.html suggests the command 
`export PYTHONPATH=${PYTHONPATH}:/${PSCFPP_DIR}/scripts/python` 
which induces the error "module pscfpp not found" when running 
`make all-cpu`.

This is because the pscfpp module isn't under pscfpp/scripts/python/, but under pscfpp/lib/python.

**Comment by dmorse** [comment]
Mateus - Thanks much for pointing this out. I released a taged version v0.8.1 to fix this bug. -David
