### ISSUE TITLE
Add commands to dump MDE solutions

### ISSUE THREAD

**Issue by dmorse** [dmorse/pscfpp#71]
Add command to pspc and pspg output full solutions of modified diffusion equation (MDE) to files.

Proposal: 

Create command WRITE_Q_RGRID with variants
       WRITE_Q_RGRID  SINGLE K L M     -> single solution (polymer K, block L, direction M)
       WRITE_Q_RGRID  BLOCK  K L         -> one block (polymer K, block L, both directions)
       WRITE_Q_RGRID  POLYMER K         -> all blocks of polymer K
        WRITE_Q_RGRID ALL                       -> all blocks of all polymers

Each solution (polymer, block, direction) will be output to a separate file with a name of the form
Q_K_L_M.qr with a header that includes information about the block length and the number ns of
contour length steps.

**Comment by rpcollanton** [comment]
This seems similar to the pull request I just made regarding the Pspc::System::writePropagatorRGrid() method. This would be certainly be better, but that method should be able to serve as a first step in this direction.

**Comment by dmorse** [comment]
Currently implemented in Pspc with the following commands, in which 
ip is polymer id, ib is block id , id is direction id (0 or 1), & is is slice/segment id:

WRITE_Q_SLICE filename ip ib id is
WRITE_Q_TAIL    filename ip ib id
WRITE_Q             filename ip ib id
WRITE_Q_ALL    basename

For WRITE_Q_ALL, the code writes all propagators for all polymers, blocks and
directions, each in a separate file with a name of the form basename_(ip)_(ib)_(id), e.g.,  out/q_0_1_0 for basename = out/q, polymer 0,
block 1, direction 0. 

Implemented in completed in commit 790710dacf20bc00a1b005da3a226afc39d11ba4
